version: '3.8'

services:
  frontend:
    image: ghcr.io/ashishu703/facial-attendence-front:latest
    container_name: facial-attendence-container
    ports:
      - "4200:443"
    restart: always

    # Yeh line zaroori hai
    extra_hosts:
      - "host.docker.internal:host-gateway"
