version: '3.8'

services:
  frontend:
    image: ghcr.io/ashishu703/facial-attendence-front:latest
    container_name: facial-attendence-container
    ports:
      - "4200:443"
    restart: always
    
    # --- YAHAN FIX HAI ---
    # 'extra_hosts' waali line HATA DEIN
    # Uski jagah yeh add karein:
    networks:
      - facial-net

# Yeh poora block file ke end mein add karein
networks:
  facial-net:
    external: true
